<?php
define("LIMIT_CPU_USER",10); //20%
define("LIMIT_CPU_MANAGER",20);
define("LIMIT_CPU_ADMIN",40);

define("LIMIT_CPU_CORE_USER",1); //核心数
define("LIMIT_CPU_CORE_MANAGER",1);
define("LIMIT_CPU_CORE_ADMIN",1);


define("LIMIT_RAM_USER",128); //20M
define("LIMIT_RAM_MANAGER",512);
define("LIMIT_RAM_ADMIN",1024);

define("LIMIT_TASK_USER",2); //2任务
define("LIMIT_TASK_MANAGER",5);
define("LIMIT_TASK_ADMIN",8);

define("LIMIT_PROCS_USER",3); //3进程
define("LIMIT_PROCS_MANAGER",8);
define("LIMIT_PROCS_ADMIN",16);

define("LIMIT_SPACE_USER",1024); //1024M
define("LIMIT_SPACE_MANAGER",2048);
define("LIMIT_SPACE_ADMIN",5120);

define("LIMIT_DBSPACE_USER",100); //100M
define("LIMIT_DBSPACE_MANAGER",200);
define("LIMIT_DBSPACE_ADMIN",512);

define("LIMIT_DOWNLOAD_USER",512); //512kb/s
define("LIMIT_DOWNLOAD_MANAGER",1024);
define("LIMIT_DOWNLOAD_ADMIN",2048);

define("LIMIT_UPLOAD_USER",512); //512kb/s
define("LIMIT_UPLOAD_MANAGER",1024);
define("LIMIT_UPLOAD_ADMIN",2048);

define("LIMIT_PROCTIME_USER",60); //60min
define("LIMIT_PROCTIME_MANAGER",1440);
define("LIMIT_PROCTIME_ADMIN",10080);
?>