<?php
header('Content-Type: application/json; charset=utf-8');
loadModule("user");
$user=new User();
if(!$user->isLogin)exitByError(5,"未登录，禁止进行操作");
if(checkGET(array("action"))){
    switch($_GET['action']){
        case "add":
            if(checkPOST(array("username","password","permission","nickname","email","phone"))){
                $data=array(
                    'username'=>array('letter+number',$_POST['username']),
                    'permission'=>array('+int',$_POST['permission']),
                    'nickname'=>array('legalString',$_POST['nickname']),
                    'email'=>array('email',$_POST['email']),
                    'phone'=>array('phone',$_POST['phone']),
                );
                $error=array(
                    'username'=>array(-6,"用户名包含特殊字符"),
                    'permission'=>array(-6,"权限错误"),
                    'nickname'=>array(-6,"昵称包含特殊字符"),
                    'email'=>array(-6,"邮箱格式错误"),
                    'phone'=>array(-6,"手机号格式错误"),
                );
                $data=checkValueType($data,$error,true);
                $profile=array(
                    'nickname'=>$data['nickname'],
                    'email'=>$data['email'],
                    'phone'=>$data['phone'],
                );
                $user->add($data['username'],$_POST['password'],$profile,$data['permission']);
                successByMsg("创建用户成功");
            }
            break;
        case "list":
            successByData("成功",$user->listUser());
            break;
        case "group":
            successByData("成功",$user->getGroup());
            break;
        case "edit":
            if(!checkGET(array("sid")))exitByError(65535,"缺失参数");
            $sid=$_GET['sid'];
            if(checkPOST(array("nickname","email","phone"))){
                $data=array(
                    'nickname'=>array('legalString',$_POST['nickname']),
                    'email'=>array('email',$_POST['email']),
                    'phone'=>array('phone',$_POST['phone']),
                );
                $error=array(
                    'nickname'=>array(-6,"昵称包含特殊字符"),
                    'email'=>array(-6,"邮箱格式错误"),
                    'phone'=>array(-6,"手机号格式错误"),
                );
                $data=checkValueType($data,$error,true);
                $profile=array(
                    'nickname'=>$data['nickname'],
                    'email'=>$data['email'],
                    'phone'=>$data['phone'],
                );
                $user->editProfile($sid,$profile);
                successByMsg("修改用户成功");
            }
            break;
        case "modifyPass":
            if(!checkGET(array("sid")))exitByError(65535,"缺失参数");
            $sid=$_GET['sid'];
            if(checkPOST(array("password"))){
                if(strlen($_POST['password'])<8)exitByError(-6,"密码至少8位");
                $user->modifyPassword($sid,$_POST['password']);
                successByMsg("修改用户密码成功");
            }
            break;
        case "modifyLimit":
            if(!checkGET(array("sid")))exitByError(65535,"缺失参数");
            $sid=$_GET['sid'];
            $modifyLimit=checkPOST(array("cpu","memory","space","task","db_space","upload","download","process","process_time"));
            $modifyPermission=checkPOST(array("permission"));
            if($modifyLimit){
                $data=array(
                    'cpu'=>array('+float',$_POST['cpu']),
                    'memory'=>array('+float',$_POST['memory']),
                    'space'=>array('+float',$_POST['space']),
                    'task'=>array('+int',$_POST['task']),
                    'db_space'=>array('+float',$_POST['db_space']),
                    'upload'=>array('+float',$_POST['upload']),
                    'download'=>array('+float',$_POST['download']),
                    'process'=>array('+int',$_POST['process']),
                    'process_time'=>array('+int',$_POST['process_time']),
                );
                $error=array(
                    'cpu'=>array(-6,"cpu数值错误"),
                    'memory'=>array(-6,"内存数值错误"),
                    'space'=>array(-6,"存储空间数值错误"),
                    'db_space'=>array(-6,"数据库空间数值错误"),
                    'upload'=>array(-6,"上传速度数值错误"),
                    'download'=>array(-6,"下载速度数值错误"),
                    'process'=>array(-6,"进程数值错误"),
                    'task'=>array(-6,"任务数值错误"),
                    'process_time'=>array(-6,"进程时间数值错误"),
                );
                $data=checkValueType($data,$error,true);
                $limit=array(
                    'cpu'=>$data['cpu'],
                    'memory'=>$data['memory'],
                    'space'=>$data['space'],
                    'task'=>$data['task'],
                    'db_space'=>$data['db_space'],
                    'upload'=>$data['upload'],
                    'download'=>$data['download'],
                    'process'=>$data['process'],
                    'process_time'=>$data['process_time'],
                );
                $permission=null;
                if($modifyPermission){
                    $dataP=array(
                        'permission'=>array('+int',$_POST['permission']),
                    );
                    $errorP=array(
                        'permission'=>array(-6,"权限错误"),
                    );
                    $dataP=checkValueType($dataP,$error,true);
                    $permission=$dataP['permission'];
                }
                $user->modifyLimit($sid,$permission,$limit);
                successByMsg("修改用户配置成功");
            }
            else if($modifyPermission){
                $data=array(
                    'permission'=>array('+int',$_POST['permission']),
                );
                $error=array(
                    'permission'=>array(-6,"权限错误"),
                );
                $data=checkValueType($data,$error,true);
                $user->modifyLimit($sid,$data['permission'],null);
                successByMsg("修改用户配置成功");
            }
            break;
        case "uploadHeader":
            $file=$user->uploadHeader();
            successByData("上传头像成功",array('header'=>PATH_USER_HEADER.$file));
            break;
        case "delete":
            if(!checkGET(array("sid")))exitByError(65535,"缺失参数");
            $sid=$_GET['sid'];
            $user->delete($sid);
            successByMsg("删除用户成功");
            break;
        case "logout":
            $user->logout();
            successByMsg("您已成功注销");
            break;
        case "info":
            $data=array();
            $data['permission']=$user->getPermissionInfo();
            $data['username']=$user->userInfo['username'];
            $data['nickname']=$user->userInfo['nickname'];
            $data['email']=$user->userInfo['email'];
            $data['phone']=$user->userInfo['phone'];
            $data['headerFile']=$user->userInfo['header'];
            $data['header']=PATH_USER_HEADER.$user->userInfo['header'];
            successByData("成功",$data);
            break;
        default:
            exitByError(72,"未知操作");
    }
    
}
exitByError(65535,"缺失参数");
?>